### ISSUE TITLE
Facebook message bot

### ISSUE THREAD

**Issue by uc-mah** [kadnan/Facebook-Chat-Bot#5]
Hi,

I am following this blog, every thing works fine. I found message on ngrok, but when i running my php script. It show below error. Please help me

Array ( [error] => Array ( [message] => (#100) The parameter user_id is required [type] => OAuthException [code] => 100 [fbtrace_id] => BLJfJGBxts8 ) )

**Comment by kadnan** [comment]
`#100) The parameter user_id is required`

**Comment by uc-mah** [comment]
not able to understand how to get it done. Every thing show on gnrok
