### ISSUE TITLE
Facebook-mes-bot

### ISSUE THREAD

**Issue by uc-mah** [kadnan/Facebook-Chat-Bot#6]
Hi,

I am following this blog, every thing works fine. I found message on ngrok, but when i running my php script. It show below error. Please help me

Array ( [error] => Array ( [message] => (#100) The parameter user_id is required [type] => OAuthException [code] => 100 [fbtrace_id] => BLJfJGBxts8 ) )

I am able to understand how to get it done. Please help me

**Comment by kadnan** [comment]
Dude why are you creating new tickets. It's clear with message what is missing. I am not into chatbot anymore so better head over to Stackoverflow
